Core/core/urls.py
from django.contrib.auth import views
from core.models import Aventura
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import home,Adventures,Luchas,rol,openWorld
from Administrador.views import Modificar,Borrar,Lista,principal,CAT,ModificarCAT,ListaCAT,DeleCAT

urlpatterns=[
    path('',home,name="home"),
    path('Aventura/',Adventures,name="Aventura"),
    path('Lucha/',Luchas,name="Peleas"),
    path('Rol/',rol,name="Rolgames"),
    path('Mundo Abierto/',openWorld,name="GTa"),
    path('principal/',principal,name="ñaco"),
    path('Lista/',Lista,name="Li"),
    path('Modificar/<id>',Modificar,name="mod"),
    path('Admin/<id>',Borrar,name="delete"),
    path('CAT/',CAT,name="cat"),
    path('ModificarCAT/<id>',ModificarCAT,name="cat"),
    path('ListaCAT',ListaCAT,name="asd"),
    path('/<id>',DeleCAT,name="deletecat"),
]

FinalTest/urls.py
from django import urls
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core.views import principal
from Administrador.views import principal as pri
from core.views import Lista
from Administrador.views import Lista as li
from core.views import Modificar
from Administrador.views import Modificar as mod
from core.views import CAT
from Administrador.views import CAT as cat
from core.views import ModificarCAT
from Administrador.views import ModificarCAT as modcat
from core.views import ListaCAT
from Administrador.views import ListaCAT as lc

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', include ('core.urls')),
    path( '', principal ),
    path('Admin/principal/',pri),
    path('Admin/Lista/',li),
    path('Admin/Modificar/<id>',mod),
    path('Admin/CAT/',cat),
    path('ModificarCAT/',modcat),
    path('ListaCAT/',lc),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Core/core/models.py
from django.db import models


class Categorias(models.Model):
    idCategoria = models.IntegerField(primary_key=True,verbose_name="Id de Categoria")
    CategoriaDejuego = models.CharField(max_length=50,verbose_name="Categoria del juego")
    

    def __str__(self):
        return self.CategoriaDejuego


class Pag1juegos(models.Model):
    Codigo = models.CharField(max_length=6, primary_key=True, verbose_name="CodigoJuego")
    NombreDelJuego = models.CharField(max_length=50,verbose_name="NombreDeljuego")
    CompañiaCreadora = models.CharField(max_length=50,verbose_name="CompañiaCreadora")
    Plataforma = models.CharField(max_length=50,null= True,blank=True,verbose_name="Plataforma")
    Descripcion = models.CharField(max_length=200,null= True,blank=True,verbose_name="Descripcion")
    Categorias = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    Caratula=models.ImageField(upload_to="Caratulas",null=True)
    def __str__(self):
        return self.NombreDelJuego

class MundoAbierto(models.Model):
    Codigo = models.CharField(max_length=6, primary_key=True, verbose_name="CodigoJuego")
    NombreDelJuego = models.CharField(max_length=50,verbose_name="NombreDeljuego")
    CompañiaCreadora = models.CharField(max_length=50,verbose_name="CompañiaCreadora")
    Plataforma = models.CharField(max_length=50,null= True,blank=True,verbose_name="Plataforma")
    Descripcion = models.CharField(max_length=200,null= True,blank=True,verbose_name="Descripcion")
    Categorias = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    Caratula=models.ImageField(upload_to="Caratulas",null=True)
    def __str__(self):
        return self.NombreDelJuego

class Rol (models.Model):
    Codigo = models.CharField(max_length=6, primary_key=True, verbose_name="CodigoJuego")
    NombreDelJuego = models.CharField(max_length=50,verbose_name="NombreDeljuego")
    CompañiaCreadora = models.CharField(max_length=50,verbose_name="CompañiaCreadora")
    Plataforma = models.CharField(max_length=50,null= True,blank=True,verbose_name="Plataforma")
    Descripcion = models.CharField(max_length=200,null= True,blank=True,verbose_name="Descripcion")
    Categorias = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    Caratula=models.ImageField(upload_to="Caratulas",null=True)
    def __str__(self):
        return self.NombreDelJuego 

class Aventura(models.Model):
    Codigo = models.CharField(max_length=6, primary_key=True, verbose_name="CodigoJuego")
    NombreDelJuego = models.CharField(max_length=50,verbose_name="NombreDeljuego")
    CompañiaCreadora = models.CharField(max_length=50,verbose_name="CompañiaCreadora")
    Plataforma = models.CharField(max_length=50,null= True,blank=True,verbose_name="Plataforma")
    Descripcion = models.CharField(max_length=200,null= True,blank=True,verbose_name="Descripcion")
    Categorias = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    Caratula=models.ImageField(upload_to="Caratulas",null=True)
    def __str__(self):
        return self.NombreDelJuego

class Lucha(models.Model):
    Codigo = models.CharField(max_length=6, primary_key=True, verbose_name="CodigoJuego")
    NombreDelJuego = models.CharField(max_length=50,verbose_name="NombreDeljuego")
    CompañiaCreadora = models.CharField(max_length=50,verbose_name="CompañiaCreadora")
    Plataforma = models.CharField(max_length=50,null= True,blank=True,verbose_name="Plataforma")
    Descripcion = models.CharField(max_length=200,null= True,blank=True,verbose_name="Descripcion")
    Categorias = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    Caratula=models.ImageField(upload_to="Caratulas",null=True)
    def __str__(self):
        return self.NombreDelJuego                                      

Core/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render
from .models import  Pag1juegos,Aventura,Lucha,Rol,MundoAbierto
from django.http import HttpResponse
# Create your views here.

def home(request):
    Juegos = Pag1juegos.objects.all()
    data = {
        'juegos':Juegos 
    }
    return render(request,'core/home.html',data)

def Adventures (request):
    JuegosAD = Aventura.objects.all()
    data = {
        'juegosad':JuegosAD
    }
    return render(request,'core/Adventures.html',data)

def Luchas (request):
    JuegosLu = Lucha.objects.all()
    data = {
        'juegoslu':JuegosLu
    }
    return render(request,'core/Luchas.html',data)    
 
def rol (request):
    JuegosRol = Rol.objects.all()
    data = {
        'juegosro':JuegosRol
    }
    return render(request,'core/rol.html',data)
    
def openWorld (request):
    JuegosMA = MundoAbierto.objects.all()
    data = {
        'juegosmu':JuegosMA
    }
    return render(request,'core/openWorld.html',data)

def principal(request):
   
    return render(request) 

def Lista(request):
    
    return render(request)


def Modificar(request):
    
    
    return render(request)

def Borrar(request):
    
    return render(request)

def CAT(request):
   
    return render(request)
    
def ModificarCAT(request):
   
    return render(request)     
    
      
def ListaCAT(request):
   
    return render(request)      

    

Core/core/templates/core/Adventures.html
{% extends 'core/base.html' %}
{% load static %}

{%block contenido%}
<h2>Juegos De Aventura</h2>
<div class="productos">
    {%for X in juegosad%}
<div class="producto">

    <div class="container">
        
        <div class="card">
            <img src="{{X.Caratula.url}}" width="100" height="100">
            <h6>{{X.Plataforma}}</h6>
            <h5 >{{X.NombreDelJuego}}</h5>
            <h6>{{X.Descripcion}}</h6>
            
        </div>
    </div>
</div>
{%endfor%}
</div>


{% endblock %}

Core/core/templates/core/Luchas.html
{% extends 'core/base.html' %}
{% load static %}

{%block contenido%}
<h2>Juegos De Lucha</h2>
<div class="productos">
    {%for X in juegoslu%}
<div class="producto">

    <div class="container">
        
        <div class="card">
            <img src="{{X.Caratula.url}}" width="100" height="100">
            <h6>{{X.Plataforma}}</h6>
            <h5 >{{X.NombreDelJuego}}</h5>
            <h6>{{X.Descripcion}}</h6>
            
        </div>
    </div>
</div>
{%endfor%}
</div>


{% endblock %}

Core/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>4FUN</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{%static 'core/css/tilos.css'%}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css'%}">
    
</head>
<body>

    
    <header id="header">
        <div class="contenedor_logo">
            <img  class="logo"  src="{%static 'core/img/logo.png'%}" alt="logo">
        </div>

        <div>
            
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{%url 'home' %}"> Inicio </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li><a href="#">Usuario:{{user.username}}</a>
                    </li>

                    <li><a href="{%url 'logout'%}">Cerrar Sesion</a>
                    </li>

                    {%if perms.app.add_mundoabierto%}
                    <li>
                        <a href="{%    url  'ñaco' %}">Agregar Juegos</a>
                    </li>
                    {%endif%}
                        
                    <li><a href="{%    url  'Li' %}">Lista De Juegos</a>    
                    {%endif%}   
                    
                    
                </ul>
            </nav>

        </div>

    </header>

    <div id="contenido">
    {% block contenido %}
    {% endblock %}
    </div>


    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script src="js/menu.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
          $('.slider').bxSlider({
              mode: 'fade',//horizontal, vertical, fade
              auto: true,
              pause: 2000
          });
        });
    </script>

</body>
</html>

Core/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{%block contenido%}

<div class="slider">
    <div>
        <img src="{%static 'core/img/banner1xd.jpg'  %}" alt="">
    </div>
    <div>
        <img src="{%static 'core/img/banner2.jpg'  %}" alt="">
    </div>
    <div>
        <img src="{%static 'core/img/banner3.jpg'  %}" alt="">
    </div>
</div>

<h2>Juegos En demostracion</h2>
<div class="productos">
    {%for X in juegos%}
<div class="producto">

    <div class="container">
       
        <div class="card">
            <img src="{{X.Caratula.url}}" width="100" height="100">
            <h6> Genero:{{X.Categorias}}</h6>
            <h4 >{{X.NombreDelJuego}}</h4>
            <a href="{{X.Categorias}}">{{X.Categorias}}</a>
        </div>
    </div>
</div>
{%endfor%}
</div>
    

{%endblock%}

Core/core/templates/core/openWorld.html
{% extends 'core/base.html' %}
{% load static %}

{%block contenido%}
<h2>Juegos De mundo abierto</h2>
<div class="productos">
    {%for X in juegosmu%}
<div class="producto">

    <div class="container">
        
        <div class="card">
            <img src="{{X.Caratula.url}}" width="100" height="100">
            <h6>{{X.Plataforma}}</h6>
            <h5 >{{X.NombreDelJuego}}</h5>
            <h6>{{X.Descripcion}}</h6>
            
        </div>
    </div>
</div>
{%endfor%}
</div>


{% endblock %}

Core/core/templates/core/rol.html
{% extends 'core/base.html' %}
{% load static %}

{%block contenido%}

<h2>Juegos De Rol</h2>
<div class="productos">
    {%for X in juegosro%}
<div class="producto">

    <div class="container">
        
        <div class="card">
            <img src="{{X.Caratula.url}}" width="100" height="100">
            <h6>{{X.Plataforma}}</h6>
            <h5 >{{X.NombreDelJuego}}</h5>
            <h6>{{X.Descripcion}}</h6>
            
        </div>
    </div>
</div>
{%endfor%}
</div>


{% endblock %}